---
kind: pipeline
type: docker
name: Build amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: Ubuntu 20.04
    image: ubuntu:focal
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/arm64/ubuntu-2004
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/arm64/ubuntu-2004
  - name: Ubuntu 18.04
    image: ubuntu:bionic
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/arm64/ubuntu-1804
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/arm64/ubuntu-1804
  - name: Debian Bullseye
    image: debian:bullseye
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/arm64/debian-11
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/arm64/debian-11
  - name: Debian Buster
    image: debian:buster
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/arm64/debian-10
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/arm64/debian-10   
  - name: Debian Stretch
    image: debian:stretch
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/arm64/debian-9
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/arm64/debian-9   
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        - dev.eris.nu
      user: root
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target: /root/
      source:
        - ./packages/*
        
---
kind: pipeline
type: docker
name: Build ARM

platform:
  os: linux
  arch: arm64
    
steps:
  - name: Ubuntu 20.04
    image: ubuntu:focal
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/arm64/ubuntu-2004
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/arm64/ubuntu-2004
  - name: Debian Bullseye
    image: debian:bullseye
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/arm64/debian-11
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/arm64/debian-11
  - name: Debian Buster
    image: debian:buster
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'
    - mkdir -p ./packages/arm64/debian-10
    - mv /tmp/hestiacp-src/deb/*.deb ./packages/arm64/debian-10   
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        - dev.eris.nu
      user: root
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target: /root/
      source:
        - ./packages/*
