---
kind: pipeline
type: docker
name: Build ARM

platform:
  os: linux
  arch: arm64
  
steps:
  - name: Ubuntu 20.04
    image: ubuntu:focal
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./src/hst_autocompile.sh --all --noinstall --keepbuild --debug '~localsrc'

