---
kind: pipeline
type: docker
name: Build ARM

platform:
  os: linux
  arch: arm64
  image: ubuntu/focal
  
steps:
  - name: Ubuntu 20.04
    commands:
      - echo "ssh_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ./src/hst_autocompile.sh --all --noinstall  --keepbuild '~localsrc'
      - scp /tmp/hestiacp-src/debs/*.deb root@dev.eris.nu:~/
  