plugin {

  #sieve_pipe_socket_dir = sieve-pipe
  #sieve_filter_socket_dir = sieve-filter
  #sieve_execute_socket_dir = sieve-execute

  #sieve_pipe_bin_dir = /usr/lib/dovecot/sieve-pipe
  #sieve_filter_bin_dir = /usr/lib/dovecot/sieve-filter
  #sieve_execute_bin_dir = /usr/lib/dovecot/sieve-execute
}

#service do-something {
  #user = dovenull

  #unix_listener sieve-pipe/do-something {
	# LDA/LMTP must have access
  #  user = vmail  
  #  mode = 0600
  #}
#}